Forward design
GroupUnifierDevelopers/GroupUnifier pull request #2
Opened 2021-09-29 19:51 UTC by Rubicman

Основные компоненты и логика для пересылки сообщений

2021-09-29 19:52 UTC, Rubicman commented
сорри за огромный пул реквест(хотя там львиная часть - тесты)

2021-10-04 19:49 UTC, ChezhegovGleb approved these changes

2021-10-06 20:50 UTC, daviondk requested changes

2021-10-06 20:50 UTC, daviondk commented on src/test/kotlin/ru/itmo/sofwaredesign/groupunifier/common/ForwarderTest.kt
> +            User("testUser", fromMockMessenger),
Лучше унести в константу, повторяется во всех тестах

2021-10-06 20:50 UTC, daviondk commented on src/test/kotlin/ru/itmo/sofwaredesign/groupunifier/common/ForwarderTest.kt
> +        chat.implementations[toMockMessenger] = "to chat id"
В целом тесты очень похожи, кажется, можно вынести общий код в какой-нибудь метод

2021-10-06 20:50 UTC, daviondk commented on src/main/kotlin/ru/itmo/sofwaredesign/groupunifier/common/Forwarder.kt
> +        } catch (e: RuntimeException) {
Не следует ловить непроверяемые исключения, тем более, все

2021-10-13 17:05 UTC, Rubicman commented on src/main/kotlin/ru/itmo/sofwaredesign/groupunifier/common/Forwarder.kt
> +        } catch (e: RuntimeException) {
Хм, но просто падать - тоже плохо, тогда нужно подумать, где этот try навернуть.

2021-10-13 17:06 UTC, Rubicman commented on src/test/kotlin/ru/itmo/sofwaredesign/groupunifier/common/ForwarderTest.kt
> +            User("testUser", fromMockMessenger),
Я думал, что тестовые данные обычно не выносятся.

2021-10-13 17:46 UTC, Rubicman commented on src/main/kotlin/ru/itmo/sofwaredesign/groupunifier/common/Forwarder.kt
> +        } catch (e: RuntimeException) {
Пока я оставлю это здесь, потому что это верхняя точка, выше которой не должны проскакивать исключения

2021-10-17 08:45 UTC, daviondk approved these changes

2021-10-17 08:52 UTC, merged